### ISSUE TITLE
`paths` are unexpectedly resolved from context

### ISSUE THREAD

**Issue by matthew-dean** [privatenumber/get-tsconfig#71] opened 2024-04-18 23:09 UTC
### Problem

This package says that it resolves extends, and is intended to work how the TypeScript compiler / language services do in figuring out your current configuration. But it doesn't do that.

Specifically, when TypeScript language services are resolving paths, any value for `paths` within `tsconfig.json` is resolved relative to the local tsconfig.json file (similar to Node resolution for modules). However, when this library is merging tsconfig configurations, it neither resolves paths nor keeps track of where those paths were declared.

This results in the "final" tsconfig having a paths definition that is altogether different from how TypeScript would resolve it, which makes the output difficult to use with a package like [alias-reuse](https://www.npmjs.com/package/alias-reuse).

The use case is that with a Nuxt setup, a sub-directory is generated with a generated tsconfig.json file. I can manually resolve those paths knowing that the path information from get-tsconfig is wrong, but I thought it would still be good to file a bug.

### Expected behavior

Either paths should fully resolve into full paths, or there should be some way to resolve those paths by knowing which file they came from OR there should be an option to do either. (Ideally, it would just resolve into the actual path.)

### Minimal reproduction URL

https://stackblitz.com/edit/stackblitz-starters-em1thz?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=tsconfig.json,package.json,index.mjs,deep%2Fdeeper%2Ftsconfig.json,deep%2Ftsconfig.json&title=node.new%20Starter

### Version

4.7.3

### Node.js version

v18.18.0

### Package manager

npm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment] 2024-04-19 03:52
I see what you mean:
```json5
❯ tsc --showConfig
{
    "compilerOptions": {
        "paths": {
            "@": [
                "../../src"
            ],
            "@/*": [
                "../../src/*"
            ]
        }
    },
    "files": [
        "./src/t.ts" // test file I added to make `tsc` work
    ]
}
```

But this deviation was a deliberate choice because users cannot use this data without the context that `../../src` is relative to `./deep/deeper/tsconfig.json`.

---

Also, please try to be concise. I usually just read the code.

**Comment by privatenumber** [comment] 2024-05-03 11:34
Closing as this is by design, and there's no follow-up proposal.

**Closed by privatenumber** 2024-05-03 11:34 UTC
Labels: bug
